<a href="https://colab.research.google.com/github/amrahmani/Pythorch/blob/main/IntroductiontoPyTorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to PyTorch Tensors**

In [2]:
# Import PyTorch library
import torch

# Create a tensor from a list of numbers
numbers = [1, 2, 3, 4, 5]
tensor = torch.tensor(numbers)

# Print the tensor information
print(tensor)  # Prints the data and tensor type (e.g., torch.tensor([1, 2, 3, 4, 5]))
print(tensor.dtype)  # Prints the data type (e.g., torch.float32)
print(tensor.shape)  # Prints the tensor shape (e.g., torch.Size([5]))

# Accessing elements
print(tensor[2])  # Access element at index 2 (3)

# Slicing a tensor
sliced_tensor = tensor[1:4]  # Get elements from index 1 to 3 (excluding 4)
print(sliced_tensor)


tensor([1, 2, 3, 4, 5])
torch.int64
torch.Size([5])
tensor(3)
tensor([2, 3, 4])


**Basic Tensor Operations**

In [3]:
# Create two tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Addition (element-wise)
c = a + b
print(c)

# Multiplication (element-wise)
d = a * b
print(d)

# In-place operations (modify the original tensor)
a.add_(5)  # Add 5 to each element of a
print(a)

# Mathematical functions (applied element-wise)
print(torch.sin(a))  # Sine of each element in a

# Dot product
dot_product = torch.dot(a, b)
print(dot_product)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([6, 7, 8])
tensor([-0.2794,  0.6570,  0.9894])
tensor(107)


Converting between Tensors and NumPy arrays

In [4]:
# Create a NumPy array
import numpy as np
numpy_array = np.array([7, 8, 9])

# Convert NumPy array to PyTorch tensor
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

# Convert PyTorch tensor to NumPy array
numpy_from_tensor = tensor_from_numpy.numpy()
print(numpy_from_tensor)


tensor([7, 8, 9])
[7 8 9]


Using NumPy operations with Tensors

In [5]:
# Create a tensor
tensor = torch.tensor([10, 11, 12])

# Use NumPy functions with the tensor (works because tensors are NumPy-like)
print(np.sqrt(tensor))  # Square root of each element
print(np.exp(tensor))  # Exponential of each element


tensor([3.1623, 3.3166, 3.4641], dtype=torch.float64)
tensor([ 22026.4658,  59874.1417, 162754.7914], dtype=torch.float64)


In [ ]:
Checking GPU availability

In [3]:
# Check if GPU is available
if torch.cuda.is_available():
    print("GPU is available!")
else:
    print("GPU is not available.")

# Move tensors to GPU (if available)
if torch.cuda.is_available():
    tensor = tensor.cuda()


GPU is available!


Performing operations on GPU (if available)

In [4]:
# Move operations to GPU if available
if torch.cuda.is_available():
    result = torch.add(tensor, tensor)  # Perform addition on GPU
    result = result.cpu()  # Move the result back to CPU for printing
    print(result)
else:
    result = torch.add(tensor, tensor)  # Perform addition on CPU
    print(result)


tensor([ 2,  4,  6,  8, 10])
