<a href="https://colab.research.google.com/github/amrahmani/NN/blob/main/SinglePerceptron_Learning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*create a single-neuron perceptron with a bias using PyTorch. The perceptron will utilize the sign activation function and train based on the delta rule with the formula: 𝑊_𝑛𝑒𝜔 = 𝑊_𝑜𝑙𝑑 + 𝛼(𝑦 - 𝑦_hat) 𝑋. Here, 'y' represents the desired output and 'y_hat' represents the predicted output. The goal is to train the network for the Boolean AND operation.\*

In [84]:
import torch

class SingleNeuron(torch.nn.Module):
    def __init__(self):
        super(SingleNeuron, self).__init__()
        # Define weights and bias
        self.W = torch.nn.Parameter(torch.randn(2, 1))
        self.b = torch.nn.Parameter(torch.randn(1))

    def forward(self, x):
        # Forward pass
        y_hat = torch.sign(torch.matmul(x, self.W) + self.b)
        return y_hat

# Define input data (Boolean AND)
X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = torch.tensor([[-1.], [-1.], [-1.], [1.]])

# Initialize model
model = SingleNeuron()

# Learning rate
alpha = 0.1

# Number of epochs
epochs = 100

# Training loop
for epoch in range(epochs):
    # Forward pass
    y_hat = model(X)

    # Compute loss
    loss = torch.mean(torch.abs(y - y_hat))

    # Update weights and bias manually
    with torch.no_grad():
        model.W.data = model.W.data + alpha * torch.matmul(X.t(), (y - y_hat))
        model.b.data = model.b.data + alpha * torch.sum(y - y_hat)

# Test the trained model
print("Trained weights:")
print(model.W)
print("Trained bias:")
print(model.b)
print("Predictions:")
print(torch.sign(model(X)))


Trained weights:
Parameter containing:
tensor([[0.3910],
        [0.3685]], requires_grad=True)
Trained bias:
Parameter containing:
tensor([-0.4470], requires_grad=True)
Predictions:
tensor([[-1.],
        [-1.],
        [-1.],
        [ 1.]], grad_fn=<SignBackward0>)
