<a href="https://colab.research.google.com/github/amrahmani/NN/blob/main/SinglePerceptron_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

create a single-neuron perceptron with a bias using PyTorch. The perceptron will utilize the sign activation function and train based on the delta rule with the formula: 𝑊_𝑛𝑒𝜔 = 𝑊_𝑜𝑙𝑑 + 𝛼(𝑦 - 𝑦_hat) 𝑋. Here, 'y' represents the desired output and 'y_hat' represents the predicted output. The goal is to train the network for the Boolean AND operation.

In [77]:
import torch

# Define input data (Boolean AND)
X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = torch.tensor([[-1.], [-1.], [-1.], [1.]])

# Initialize weights and bias randomly
W_old = torch.randn(2, 1)
b_old = torch.randn(1)

# Learning rate
alpha = 0.1

# Number of epochs
epochs = 50

# Training loop
for epoch in range(epochs):
    # Forward pass
    y_hat = torch.sign(torch.matmul(X, W_old) + b_old)

    # Compute loss
    loss = torch.mean(torch.abs(y - y_hat))

    # Update weights and bias
    W_new = W_old + alpha * torch.matmul(X.t(), (y - y_hat))
    b_new = b_old + alpha * torch.sum(y - y_hat)

    # Update weights and bias for the next iteration
    W_old.data = W_new.data
    b_old.data = b_new.data

# Test the trained model
print("Trained weights:")
print(W_new)
print("Trained bias:")
print(b_new)
print("Predictions:")
print(torch.sign(torch.matmul(X, W_new) + b_new))


Trained weights:
tensor([[0.4703],
        [0.2621]])
Trained bias:
tensor([-0.6159])
Predictions:
tensor([[-1.],
        [-1.],
        [-1.],
        [ 1.]])
